-- Estrutura inicial do banco Oracle.
-- Revisar nomes e tipos antes da versão final da entrega.

CREATE TABLE areas_agricolas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_area VARCHAR2(100) NOT NULL,
    cultura VARCHAR2(50) NOT NULL,
    area_hectares NUMBER(10,2) NOT NULL,
    ph NUMBER(4,2),
    nitrogenio NUMBER(10,2),
    fosforo NUMBER(10,2),
    potassio NUMBER(10,2),
    observacoes VARCHAR2(500)
);
